### ISSUE TITLE
Should not try to create link `/usr/local/lib/README.md`

### ISSUE THREAD

**Issue by FranklinChen** [hamler-lang/homebrew-hamler#2]
It seems to me that the Homebrew formula should not be trying to create the link `/usr/local/lib/README.md` (and I should not have had such a file there anyway either).

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink lib/README.md
Target /usr/local/lib/README.md
already exists. You may want to remove it:
  rm '/usr/local/lib/README.md'

To force the link and overwrite all conflicting files:
  brew link --overwrite hamler

To list all files that would be deleted:
  brew link --overwrite --dry-run hamler

Possible conflicting files are:
/usr/local/lib/README.md
```

**Comment by Rory-Z** [comment]
Hi, @FranklinChen 
Hamler will not create the `READme.md` file. I don't think hamler is responsible for your error

**Comment by FranklinChen** [comment]
The log above shows what hamler is trying to do.

Also, here is what I have on my Mac after installing hamler:
```
➜  ~ ls -lt /usr/local/lib/README.md
lrwxr-xr-x  1 chen  staff  36 Jun 18 13:14 /usr/local/lib/README.md -> ../Cellar/hamler/0.1.2/lib/README.md
```

**Comment by Rory-Z** [comment]
Hi, @FranklinChen 
Sorry, this is an oversight, we will delete it in the next version

**Comment by Rory-Z** [comment]
Hi, @FranklinChen 
We have solved this issue in 0.1.3, welcome to use 0.1.3

**Comment by FranklinChen** [comment]
Thanks!

**Comment by Rory-Z** [comment]
You're welcome :)
